conky.config = {
    update_interval = 1,
    double_buffer = true,

    own_window = true,
    own_window_type = 'normal',
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_transparent = true,

    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    alignment = 'middle_middle',
    gap_x = 0,
    gap_y = 0,

    minimum_width = 260,
    minimum_height = 80,

    use_xft = true,
    font = 'DejaVu Sans:bold:size=22',
    xftalpha = 1,
};

conky.text = [[
    ${image images/theme/bg/red.png -p 0,0 -s 260x380}
    ${goto 40}${voffset -65}${color white}CPU${color}
    ${voffset 10}${cpugraph 120,260 ffffff ffffff}
]]
